:_mod-docs-content-type: ASSEMBLY
[id="update-using-custom-machine-config-pools"]
= Performing a canary rollout update
include::_attributes/common-attributes.adoc[]
:context: update-using-custom-machine-config-pools

toc::[]

[role="_abstract"]
For a more controlled rollout of worker node updates, you can use a _canary update_.
A canary update is an update strategy where worker node updates are performed in discrete, sequential stages instead of updating all worker nodes at the same time.

This strategy can be useful in the following scenarios:

* You want a more controlled rollout of worker node updates to ensure that mission-critical applications stay available during the entire update, even if the update process causes your applications to fail.
* You want to update a small subset of worker nodes, evaluate cluster and workload health over a period of time, and then update the remaining nodes.
* You want to fit worker node updates, which often require a host reboot, into smaller defined maintenance windows when it is not possible to take a large maintenance window to update the entire cluster at one time.

In these scenarios, you can create multiple custom machine config pools (MCPs) to prevent certain worker nodes from updating when you update the cluster.
After the rest of the cluster is updated, you can update those worker nodes in batches at appropriate times.

include::modules/update-canary-example.adoc[leveloffset=+1]

include::modules/update-canary-about.adoc[leveloffset=+1]

// About performing a canary rollout update
include::modules/update-using-custom-machine-config-pools-about.adoc[leveloffset=+1]

// Creating machine config pools to perform a canary rollout update
include::modules/update-using-custom-machine-config-pools-mcp.adoc[leveloffset=+1]

// Managing machine configuration inheritance for a worker pool canary
include::modules/update-using-custom-machine-config-pools-inheritance.adoc[leveloffset=+1]

// Pausing the machine config pools
include::modules/update-using-custom-machine-config-pools-pause.adoc[leveloffset=+1]

include::modules/update-canary-performing.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* xref:../../updating/updating_a_cluster/updating-cluster-web-console.adoc#update-upgrading-web_updating-cluster-web-console[Updating a cluster using the web console]
* xref:../../updating/updating_a_cluster/updating-cluster-cli.adoc#update-upgrading-cli_updating-cluster-cli[Updating a cluster using the CLI]

// Unpausing the machine config pools
include::modules/update-using-custom-machine-config-pools-unpause.adoc[leveloffset=+1]

// Moving a node to the original machine config pool
include::modules/update-using-custom-machine-config-pools-mcp-remove.adoc[leveloffset=+1]
