:_mod-docs-content-type: ASSEMBLY
[id="approved-access"]
= Approved access

include::_attributes/common-attributes.adoc[]
ifdef::openshift-dedicated[]
include::_attributes/attributes-openshift-dedicated.adoc[]
endif::[]
:context: approved-access

toc::[]

[role="_abstract"]
With Red{nbsp}Hat Site Reliability Engineering (SRE), you typically do not need elevated access to systems to do normal operations to manage and support your {product-title} clusters. If you have elevated access, you can give SRE the access levels of a cluster-admin role.

In the unlikely event that SRE needs elevated access to systems, use the _Approved Access_ interface to review and _approve_ or _deny_ access to these systems. SRE can create elevated access requests to {product-rosa} clusters and the corresponding cloud accounts in response to a customer-initiated support ticket or to alerts as part of the standard incident response process.  

When you enable _Approved Access_ and an SRE creates an access request, _cluster owners_ receive an email notification informing them of a new access request. The email notification has a link allowing the cluster owner to approve or deny the access request. If you do not respond to this request, there is a risk to your service-level agreement (SLA) for {product-rosa}. 

[NOTE]
====
Denying an access request requires you to complete the *Justification* field. In this case, SRE cannot directly act on the resources related to the incident. Customers can still use the *Red Hat Customer Support* resource to help investigate and resolve any issues.
====

include::modules/support-submitting-a-case-enable-approved-access.adoc[leveloffset=+1]

include::modules/support-reviewing-an-access-request-from-an-email-notification.adoc[leveloffset=+1]

include::modules/support-reviewing-an-access-request-from-the-hybrid-console.adoc[leveloffset=+1]

[role="_additional-resources"]
[id="additional-resources_{context}"]
== Additional resources

* link:https://docs.openshift.com/container-platform/latest/authentication/using-rbac.html#default-roles_using-rbac[Cluster roles]                                           
* xref:../rosa_cluster_admin/rosa-cluster-notifications.adoc#add-notification-contact_rosa-cluster-notifications[Adding notification cluster contacts]
* link:https://access.redhat.com/support/cases/#/case/list[Red Hat Customer Support]