:_mod-docs-content-type: ASSEMBLY
[id="about-migrating-from-3-to-4"]
= About migrating from {product-title} 3 to 4
include::_attributes/common-attributes.adoc[]
:context: about-migrating-from-3-to-4

toc::[]

{product-title} 4 contains new technologies and functionality that result in a cluster that is self-managing, flexible, and automated. {product-title} 4 clusters are deployed and managed very differently from {product-title} 3.

The most effective way to migrate from {product-title} 3 to 4 is by using a CI/CD pipeline to automate deployments in an link:https://www.redhat.com/en/topics/devops/what-is-application-lifecycle-management-alm[application lifecycle management] framework.

You can use Red Hat Advanced Cluster Management for Kubernetes to help you import and manage your {product-title} 3 clusters easily, enforce policies, and redeploy your applications. Take advantage of the link:https://www.redhat.com/en/engage/free-access-redhat-e-202202170127[free subscription] to use Red Hat Advanced Cluster Management to simplify your migration process.

To successfully transition to {product-title} 4, review the following information:

xref:../migrating_from_ocp_3_to_4/planning-migration-3-4.adoc#planning-migration-3-4[Differences between {product-title} 3 and 4]::
* Architecture
* Installation and upgrade
* Storage, network, logging, security, and monitoring considerations
