// Module included in the following assemblies:
//
// * networking/hardware_networks/configuring-sriov-operator.adoc

:_mod-docs-content-type: CONCEPT
[id="about-sr-iov-operator-admission-control-webhook_{context}"]
= About the SR-IOV Network Operator admission controller webhook

[role="_abstract"]
You can use the SR-IOV Network Operator Admission Controller webhook to mutate or validate the `SriovNetworkNodePolicy` CR.

* Validation of the `SriovNetworkNodePolicy` CR when it is created or updated.
* Mutation of the `SriovNetworkNodePolicy` CR by setting the default value for the `priority` and `deviceType` fields when the CR is created or updated.

The SR-IOV Network Operator Admission Controller webhook is enabled by the Operator when the `enableOperatorWebhook` is set to `true` in the `SriovOperatorConfig` CR. The `operator-webhook` pod runs as a daemon set on all control plane nodes.

[NOTE]
====
Use caution when disabling the SR-IOV Network Operator Admission Controller webhook. You can disable the webhook under specific circumstances, such as troubleshooting, or if you want to use unsupported devices. For information about configuring unsupported devices, see "Configuring the SR-IOV Network Operator to use an unsupported NIC".
====

The following is an example of the Operator Admission Controller webhook pods running in a cluster with three control plane nodes:

[source,terminal]
----
$ oc get pods -n openshift-sriov-network-operator
----

.Example output
[source,terminal]
----
NAME                                      READY   STATUS    RESTARTS   AGE
operator-webhook-9jkw6                    1/1     Running   0          16m
operator-webhook-kbr5p                    1/1     Running   0          16m
operator-webhook-rpfrl                    1/1     Running   0          16m
----

