// Module included in the following assemblies:
//
// * security/cert_manager_operator/cert-manager-trust-manager.adoc

:_mod-docs-content-type: PROCEDURE
[id="cert-manager-trust-manager-uninstall_{context}"]
= Uninstalling the trust-manager operand

[role="_abstract"]
You can uninstall the trust-manager operand by deleting the TrustManager custom resource (CR). Deleting the TrustManager CR stops the operator from reconciling trust-manager resources, but does not automatically remove the trust-manager deployment or its associated resources. You must manually delete these resources after deleting the CR if you need a complete cleanup.

.Prerequisites

* You have access to the cluster with `cluster-admin` privileges.
* You have enabled the trust manager feature.
* You have created the `TrustManager` custom resource.

.Procedure

. Delete any Bundle CRs that you created. Deleting a Bundle CR causes trust-manager to remove the corresponding target ConfigMap and Secret objects from the target namespaces.

.. Fetch the list of bundles created by running the following command:
+
[source,terminal]
----
$ oc get Bundle
----

.. Delete each Bundle in the list by running the following command:
+
[source,terminal]
----
$ oc delete Bundle <bundle_name>
----

. Delete the `TrustManager` custom resource by running the following command:
+
[source,terminal]
----
$ oc delete TrustManager cluster
----

. Delete all the labeled resources to complete the cleanup:

.. Delete the namespace-scoped resources in the `cert-manager` namespace:
+
[source,terminal]
----
$ oc delete deployments,services,serviceaccounts,configmaps,certificates,issuers -l "app.kubernetes.io/name=cert-manager-trust-manager" -n cert-manager
----
.. Delete the cluster-scoped resources:
+
[source,terminal]
----
$ oc delete clusterroles,clusterrolebindings,validatingwebhookconfigurations -l "app.kubernetes.io/name=cert-manager-trust-manager"
----
.. If you configured a custom trust namespace, delete the role and role binding resources in that namespace:
+
[source,terminal]
----
$ oc delete roles,rolebindings -l "app.kubernetes.io/name=cert-manager-trust-manager" -n <trust_namespace>
----