// Module included in the following assemblies:
// * edge_computing/image-based-upgrade/cnf-image-based-upgrade-base.adoc

:_mod-docs-content-type: PROCEDURE
[id="ztp-image-based-upgrade-prep_{context}"]
= Moving to the Prep stage of the image-based upgrade with {lcao}

[role="_abstract"]
When you deploy the {lcao} on a cluster, the {lcao} automatically creates an `ImageBasedUpgrade` custom resource (CR).

After you create all the resources that you need during the upgrade, you can move on to the `Prep` stage.
For more information, see the "Creating ConfigMap objects for the image-based upgrade with {lcao}" section.

[NOTE]
====
In a disconnected environment, if the seed cluster's release image registry is different from the target cluster's release image registry, you must create an `ImageDigestMirrorSet` (IDMS) resource to configure alternative mirrored repository locations. For more information, see "Configuring image registry repository mirroring". 

You can retrieve the release registry used in the seed image by running the following command:

[source,terminal]
----
$ skopeo inspect docker://<imagename> | jq -r '.Labels."com.openshift.lifecycle-agent.seed_cluster_info" | fromjson | .release_registry'
----
====

.Prerequisites

* You have created resources to back up and restore your clusters.

.Procedure

. Check that you have patched your `ImageBasedUpgrade` CR:
+
[source,yaml]
----
apiVersion: lca.openshift.io/v1
kind: ImageBasedUpgrade
metadata:
  name: upgrade
spec:
  stage: Idle
  seedImageRef:
    version: <target_version>
    image: <seed_container_image>
    pullSecretRef: <seed_pull_secret>
  autoRollbackOnFailure: {}
    initMonitorTimeoutSeconds: <initMonitorTimeoutSeconds>
  extraManifests:
  - name: example-extra-manifests-cm
    namespace: openshift-lifecycle-agent
  - name: example-catalogsources-cm
    namespace: openshift-lifecycle-agent
  oadpContent:
  - name: oadp-cm-example
    namespace: openshift-adp
----
+
where:
+
`<target_version>`:: Target platform version. The value must match the version of the seed image.
`<seed_container_image>`:: Repository where the target cluster can pull the seed image from.
`<seed_pull_secret>`:: Reference to a secret with credentials to pull container images if the images are in a private registry.
`<initMonitorTimeoutSeconds>`:: Optional: Time frame in seconds to roll back if the upgrade does not complete within that time frame after the first reboot. If not defined or set to `0`, the {lcao} uses the default value of `1800` seconds (30 minutes).
`extraManifests`:: Optional: List of `ConfigMap` resources. These resources contain your custom catalog sources to retain after the upgrade and any extra manifests that the seed image does not include.
`oadpContent`:: List of `ConfigMap` resources that contain the {oadp-short} `Backup` and `Restore` CRs.

. To start the `Prep` stage, change the value of the `stage` field to `Prep` in the `ImageBasedUpgrade` CR by running the following command:
+
--
[source,terminal]
----
$ oc patch imagebasedupgrades.lca.openshift.io upgrade -p='{"spec": {"stage": "Prep"}}' --type=merge -n openshift-lifecycle-agent
----

If you include `ConfigMap` objects for {oadp-short} resources and extra manifests, {lcao} validates the specified `ConfigMap` objects during the `Prep` stage.

The following issues might occur:

* Validation warnings or errors if the {lcao} detects any issues with the `extraManifests` parameters.
* Validation errors if the {lcao} detects any issues with the `oadpContent` parameters.

Validation warnings do not block the `Upgrade` stage but you must decide if it is safe to proceed with the upgrade.
These warnings, for example missing custom resource definitions (CRDs), namespaces, or dry run failures, update the `status.conditions` for the `Prep` stage and `annotation` fields in the `ImageBasedUpgrade` CR with details about the warning. The following example shows these details:

[source,yaml]
----
# ...
metadata:
annotations:
  extra-manifest.lca.openshift.io/validation-warning: '...'
# ...
----

However, validation errors, such as adding `MachineConfig` or Operator manifests to extra manifests, cause the `Prep` stage to fail and block the `Upgrade` stage.

When the validations pass, the cluster creates a new `ostree` stateroot, which involves pulling and unpacking the seed image, and running host-level commands.
Finally, the {lcao} precaches all the required images on the target cluster.
--

.Verification

* Check the status of the `ImageBasedUpgrade` CR by running the following command:
+
--
[source,terminal]
----
$ oc get ibu -o yaml
----

The following example shows a successful `Prep` stage:

[source,yaml]
----
  conditions:
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: In progress
    observedGeneration: 13
    reason: InProgress
    status: "False"
    type: Idle
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: Prep completed
    observedGeneration: 13
    reason: Completed
    status: "False"
    type: PrepInProgress
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: Prep stage completed successfully
    observedGeneration: 13
    reason: Completed
    status: "True"
    type: PrepCompleted
  observedGeneration: 13
  validNextStages:
  - Idle
  - Upgrade
----
--