// Module included in the following assemblies:
//
// * networking/ingress_load_balancing/configuring_ingress_cluster_traffic/routing-grpc-requests-to-services.adoc

:_mod-docs-content-type: PROCEDURE
[id="configuring-routing-destinations-traffic-weights-grpc_{context}"]
= Configure routing destinations and traffic weights for gRPC

[role="_abstract"]
When you route gRPC traffic, you must define backend service destinations and traffic weights to distribute requests across your APIs. `BackendRefs` designate the backend services where matching and filtered gRPC requests are delivered.

You can configure optional backend references for each routing rule. By defining multiple backend references and assigning a `weight` to each, you can control the proportion of gRPC traffic that is forwarded to specific versions of your service. The proportion of traffic sent to a specific backend is calculated by dividing its assigned weight by the sum of all weights across all backends configured in the rule.

Because {SMProductName} handles the data-plane behavior, you must ensure that your `GRPCRoute` references an Istio ingress gateway in its `parentRefs` configuration.

.Prerequisites

* You have access to the cluster as a user with the `cluster-admin` role.
* You have installed the {oc-first}.
* You have installed {SMProductName}.

.Procedure

. Create or edit a `GRPCRoute` YAML file to include your desired service destinations and traffic weights under the `spec.rules.backendRefs` field.
+
--
The following example demonstrates a complete `GRPCRoute` resource that routes gRPC traffic between two versions of a backend service using proportional traffic weights:

[source,yaml]
----
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: grpc-weight-example
  namespace: my-application
spec:
  parentRefs:
  - name: my-gateway
    namespace: openshift-ingress
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: greeter-service-v1
      port: 50051
      weight: 90
    - name: greeter-service-v2
      port: 50051
      weight: 10
----
* `parentRefs` attaches the route to the `my-gateway` Gateway.
* `backendRefs` defines the destination services for the traffic.
* `weight` dictates the traffic split. In this configuration, the total sum of the weights is 100. The route forwards 90% of the traffic to `greeter-service-v1` and 10% to `greeter-service-v2`. 
--

. Apply the `GRPCRoute` resource by running the following command:
+
[source,terminal]
----
$ oc apply -f <filename>.yaml
----