// Module included in the following assemblies:
//
// * scalability_and_performance/ibm-z-recommended-host-practices.adoc

:_mod-docs-content-type: PROCEDURE
[id="disabling-the-cpuset-cgroup-controller_{context}"]
= Disabling the cpuset cgroup controller

[role="_abstract"]
You can disable the cpuset cgroup controller. Disabling the controller requires a restart of the libvirtd daemon. 

[NOTE]
====
This setting applies only to KVM hosts with cgroups version 1. To enable CPU hotplug on the host, disable the cgroup controller.
====

.Procedure

. Open `/etc/libvirt/qemu.conf` with an editor of your choice.

. Go to the `cgroup_controllers` line.

. Duplicate the entire line and remove the leading number sign (#) from the copy.

. Remove the `cpuset` entry, as follows:
+
[source,config]
----
cgroup_controllers = [ "cpu", "devices", "memory", "blkio", "cpuacct" ]
----

. For the new setting to take effect, you must restart the libvirtd daemon:
+
.. Stop all virtual machines.
+
.. Run the following command:
+
[source,terminal]
----
# systemctl restart libvirtd
----
+
.. Restart the virtual machines.
+
This setting persists across host reboots.
