// Module included in the following assemblies:
//
// * hosted_control_planes/hcp-deploy/hcp-deploy-bm.adoc
// * hosted_control_planes/hcp-deploy/hcp-deploy-aws.adoc
// * hosted_control_planes/hcp-deploy/hcp-deploy-ibmz.adoc
// * hosted_control_planes/hcp-deploy/hcp-deploy-ibm-power.adoc

:_mod-docs-content-type: PROCEDURE
[id="hcp-nodeport-config_{context}"]
= Configuring the node port before you create a hosted cluster

[role="_abstract"]
Cluster administrators can configure ingress settings during installation so that they can set up load balancers before they create a hosted cluster. 

If you run external load balancers, and the default setting is to randomize the node port that the service exposes the ingress on, which is impossible to predict and hard to automate. Instead, you can configure the node port at installation, so that you can configure the load balancer before you set up the hosted cluster.

To configure how the ingress controller publishes the default ingress route, set the `endpointPublishingStrategy` parameter and its underlying functions.

.Prerequisites

.Procedure


.Example configuration on a `HostedCluster` resource
[source,yaml]
----
spec:
  operatorConfiguration:
    ingressOperator:
      endpointPublishingStrategy:
        hostNetwork:
          httpPort: 80
          httpsPort: 443
          protocol: TCP
          statsPort: 1936
        type: HostNetwork
----

The `endpointPublishingStrategy` spec then reuses the general ingress controller spec. {hcp-capital} supports only the `HostNetwork` type for bare metal, not other possible types, such as `LoadBalancerService` or `NodePortService`.
