// Module included in the following assemblies:
//
// * list of assemblies where this module is included 
// ** support/remote_health_monitoring/insights-operator-simple-access.adoc

:_mod-docs-content-type: CONCEPT
[id="insights-operator-sca-entitlement-synchronization_{context}"]
= Simple Content Access entitlement synchronization

[role="_abstract"]
Simple Content Access (SCA) simplifies subscription management by removing the requirement to manually attach entitlement keys to individual nodes. {insights-operator} facilitates this by automatically retrieving and storing certificates as secrets within the `openshift-config-managed` namespace. These certificates allow the cluster to authenticate with Red{nbsp}Hat content repositories for operations such as entitled builds.

Entitlement secrets refresh automatically every 8 hours. While older configurations used a support secret in the `openshift-config` namespace, {insights-operator} now prioritizes the `insights-config` `ConfigMap` in the `openshift-insights` namespace if both exist.

[NOTE]
==== 
Simple content access must be enabled in Red{nbsp}Hat Subscription Management for the importing to function.
====
