// Module included in the following assemblies:
//
// * list of assemblies where this module is included 
// ** support/remote_health_monitoring/insights-operator-simple-access.adoc

:_mod-docs-content-type: PROCEDURE
[id="insights-operator-verify-manage-entitlement-secrets_{context}"]
= Verify and manage entitlement secrets

[role="_abstract"]
To verify the imported entitlement secrets, list architecture-specific secrets and change the import behavior with the {insights-Operator} configuration.

.Prerequisites

* You have cluster-admin permissions for the {product-title} cluster.
* You have set Simple Content Access (SCA) to *Enabled* in the {hybrid-console} or your Red{nbsp}Hat Satellite instance.
* You have registered the cluster with {cluster-manager-first} and have an active connection to the internet or a proxy to reach Red{nbsp}Hat services.
* You have confirmed that the `insights-config` `ConfigMap` exists in the `openshift-insights` namespace.

.Procedure

* To list the secrets in the `openshift-config-managed` namespace, run the following command in a terminal:
+
[source,terminal]
----
$ oc get secrets -n openshift-config-managed | grep etc-pki-entitlement
----

.Verification

* Verify that the secrets match the cluster architecture (for example, `-amd64` or `-arm64`) by checking the output of the list command to ensure the relevant secrets are present. The output shows secrets that include the name of the cluster's architecture, and look similar to the following:
+
[source,terminal]
----
etc-pki-entitlement                 Opaque                    2      28h
etc-pki-entitlement-amd64           Opaque                    2      88s
etc-pki-entitlement-arm64           Opaque                    2      88s
----
