// Module included in the following assemblies:
//
// * installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.adoc
// * installing/installing_vsphere/installing-restricted-networks-installer-provisioned-vsphere.adoc

ifeval::["{context}" == "installing-vsphere"]
:vsphere-upi:
endif::[]
ifeval::["{context}" == "installing-restricted-networks-vsphere"]
:vsphere-upi:
endif::[]
ifeval::["{context}" == "installing-vsphere-network-customizations"]
:vsphere-upi:
endif::[]

:_mod-docs-content-type: REFERENCE
[id="installation-vsphere-config-yaml_{context}"]
= Sample install-config.yaml file for a {vmw-first} cluster

[role="_abstract"]
You can customize the `install-config.yaml` file to specify more details about your {product-title} cluster's platform or change the values of the required parameters.

[IMPORTANT]
====
Carefully review the "Installation configuration parameters for {vmw-short}" page for detailed parameter explanations.
====

[source,yaml]
----
apiVersion: v1
baseDomain: example.com
metadata:
  name: test
sshKey: ssh-ed25519 AAAA...
compute:
- name:  <worker_name>
  platform: {}
ifdef::vsphere-upi[]
  replicas: 0
endif::vsphere-upi[]
ifndef::vsphere-upi[]
  replicas: 3
endif::vsphere-upi[]
controlPlane:
  name: <control_plane_name>
  platform: {}
  replicas: 3
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
platform:
  vsphere:
ifndef::vsphere-upi[]
    apiVIPs:
    - 10.0.0.1
    ingressVIPs:
    - 10.0.0.2
endif::vsphere-upi[]
    failureDomains:
    - name: <failure_domain_name>
      region: <default_region_name>
      server: <fully_qualified_domain_name>
      topology:
        computeCluster: "/<data_center>/host/<cluster>"
        datacenter: <data_center>
        datastore: "/<data_center>/datastore/<datastore>"
        networks:
        - <VM_Network_name>
      zone: <default_zone_name>
    vcenters:
    - datacenters:
      - <data_center>
      server: <fully_qualified_domain_name>
      user: administrator@vsphere.local
----
where:

`compute`:: Specifes the parameters that apply to compute nodes.
`controlPlane`:: Specifies the parameters that apply to control plane nodes.
`networking`:: Specifies the parameters that apply to cluster networking configuration.
`platform`:: Specifies the parameters that apply to the configuration of the platform hosting the cluster.

ifeval::["{context}" == "installing-vsphere"]
:!vsphere-upi:
endif::[]
ifeval::["{context}" == "installing-restricted-networks-vsphere"]
:!vsphere-upi:
endif::[]
ifeval::["{context}" == "installing-vsphere-network-customizations"]
:!vsphere-upi:
endif::[]