// Module included in the following assemblies:

// * updating/updating_a_cluster/updating-cluster-web-console.adoc

:_mod-docs-content-type: PROCEDURE
[id="machine-health-checks-pausing-web-console_{context}"]
= Pausing a MachineHealthCheck resource by using the web console

[role="_abstract"]
During the update process, nodes in the cluster might become temporarily unavailable. For worker nodes, the machine health check might identify such nodes as unhealthy and reboot them. To avoid rebooting such nodes, pause all the `MachineHealthCheck` resources before updating the cluster.

.Prerequisites

* You have access to the cluster with `cluster-admin` privileges.
* You have access to the {product-title} web console.

.Procedure

. On the web console, navigate to *Compute* -> *MachineHealthChecks*.
. For each `MachineHealthCheck` resource, pause the machine health checks by adding the `cluster.x-k8s.io/paused=""` annotation to the resource. For example, to add the annotation to the `machine-api-termination-handler` resource, complete the following steps:
.. Click the Options menu {kebab} next to the `machine-api-termination-handler` and click *Edit annotations*.
.. In the *Edit annotations* dialog, click *Add more*.
.. In the *Key* and *Value* fields, add `cluster.x-k8s.io/paused` and `""` values, respectively, and click *Save*.
