// Module included in the following assemblies:
//
// * machine_management/creating_machinesets/creating-machineset-azure.adoc
// * machine_management/creating_machinesets/creating-machineset-azure-stack-hub.adoc
// * machine_management/control_plane_machine_management/cpmso_provider_configurations/cpmso-config-options-azure.adoc

ifeval::["{context}" == "creating-machineset-azure-stack-hub"]
:ash:
endif::[]

:_mod-docs-content-type: PROCEDURE
[id="machineset-azure-boot-diagnostics_{context}"]
= Enabling {azure-first} boot diagnostics

[role="_abstract"]
You can enable boot diagnostics on {azure-full} machines that your machine set creates. Use this to store console logs that you can use to troubleshoot why a node fails to boot.

.Prerequisites

* Have an existing {azure-short}
ifdef::ash[Stack Hub]
cluster.

.Procedure

* Add the `diagnostics` configuration that is applicable to your storage type to the `providerSpec` field in your machine set YAML file:

** For an {azure-short} Managed storage account:
+
[source,yaml]
----
providerSpec:
  value:
    diagnostics:
      boot:
        storageAccountType: <azure_managed>
----
+
where:
+
--
`<azure_managed>`:: Specifies an {azure-short} Managed storage account.
--

** For an {azure-short} Unmanaged storage account:
+
[source,yaml]
----
providerSpec:
  value:
    diagnostics:
      boot:
        storageAccountType: <customer_managed>
        customerManaged:
          storageAccountURI: <https://<storage_account>.blob.core.windows.net>
----
+
where:
+
--
`<customer_managed>`:: Specifies an {azure-short} Unmanaged storage account.
`\https://<storage_account>.blob.core.windows.net`:: Specifies the storage account URL. Replace `<storage_account>` with the name of your storage account.
--
+
[NOTE]
====
Only the {azure-short} Blob Storage data service is supported.
====

.Verification

* On the {azure-short} portal, review the *Boot diagnostics* page for a machine deployed by the machine set, and verify that you can see the serial logs for the machine.

ifeval::["{context}" == "creating-machineset-azure-stack-hub"]
:!ash:
endif::[]