// Module included in the following assemblies:
//
// * microshift_configuring/microshift-ingress-controller.adoc

:_mod-docs-content-type: PROCEDURE
[id="microshift-ingress-controller-config_{context}"]
= Configuring the TLS security profile for the ingress controller

[role="_abstract"]
To configure the TLS security profile for the ingress controller in {microshift-short}, you can add the `spec.tlsSecurityProfile` field to the configuration YAML and set a value for the appropriate profile. To apply the changes, restart the service.

.Prerequisites

* You have root access to the {microshift-short} node.

.Procedure

. Add the `spec.tlsSecurityProfile` field to the {microshift-short} YAML configuration file.
+
[source,yaml]
----
 ...
spec:
  tlsSecurityProfile:
    type: Custom
    custom:
      ciphers:
      - ECDHE-ECDSA-CHACHA20-POLY1305
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES128-GCM-SHA256
      minTLSVersion: VersionTLS11
 ...
----
+
where:

`spec.tlsSecurityProfile.type`:: Specifies the TLS security profile type (`Old`, `Intermediate`, or `Custom`). The default is `Intermediate`.
`spec.tlsSecurityProfile.custom`:: Specifies the appropriate field for the selected type:
** `old: {}`
** `intermediate: {}`
** `custom:`
`spec.tlsSecurityProfile.custom.ciphers`:: Specifies a list of TLS ciphers and minimum accepted TLS version.
+
[WARNING]
====
If you choose a `custom` TLS configuration, use extreme caution. Using self-signed TLS certificates can introduce security risks.
====

. Save the file to apply the changes.

. Restart {microshift-short} by running the following command:
+
[source,terminal]
----
$ sudo systemctl restart microshift
----
