// Module included in the following assemblies:
//
// * microshift//running_applications/microshift-deleting-resource-manifests.adoc

:_mod-docs-content-type: PROCEDURE
[id="microshift-manifests-removal-scenario-rpm_{context}"]
= Removing manifests for RPM systems

[role="_abstract"]
To remove a resource on RPM-based {microshift-short} systems, move the manifest into a `delete` subdirectory and restart {microshift-short} so the resource is deleted.

.Procedure

. Identify the manifest that needs to be placed in the `delete` subdirectories.
. Create the `delete` subdirectory in which the manifest will be placed by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ sudo mkdir -p _<path_of_delete_directory>_
----
+
Replace `_<path_of_delete_directory>_` with one of the following valid directory paths: `/etc/microshift/manifests.d/delete`, `/etc/microshift/manifests/delete/`, `/usr/lib/microshift/manifests.d/delete`, or `/usr/lib/microshift/manifests/delete`.
. Move the manifest file into one of the `delete` subdirectories under the configured manifests directory by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ [sudo] mv _<path_of_manifests>_ _<path_of_delete_directory>_
----
+
where:

`_<path_of_manifests>_`:: Specifies the path of the manifest to be deleted, for example `/etc/microshift/manifests.d/010-SOME-MANIFEST`.
`_<path_of_delete_directory>_`:: Specifies one of the following valid directory paths: `/etc/microshift/manifests.d/delete`, `/etc/microshift/manifests/delete`, `/usr/lib/microshift/manifests.d/delete` or `/usr/lib/microshift/manifests/delete`.
. Restart {microshift-short} by running the following command:
+
[source,terminal]
----
$ sudo systemctl restart microshift
----
. {microshift-short} detects and removes the resource after the manifest file is placed in the `delete` subdirectories.