// Module included in the following assemblies:
//
// * updating/updating_a_cluster/migrating-to-multi-payload.adoc

:_mod-docs-content-type: PROCEDURE
[id="migrating-to-multi-arch-cli_{context}"]
= Migrating to a cluster with multi-architecture compute machines using the CLI

[role="_abstract"]
You can use the {oc-first} to migrate to a cluster with multi-architecture compute machines.


.Prerequisites

* You have access to the cluster as a user with the `cluster-admin` role.
* Your {product-title} version is 4.13.0 or later.
+
For more information on how to update your cluster version, see "Updating a cluster using the web console" or "Updating a cluster using the CLI".
* You have installed the {oc-first} that matches the version for your current cluster.
* Your `oc` client is updated to version 4.13.0 or later.
* Your {product-title} cluster is installed on AWS, Azure, {gcp-short}, bare metal, or IBM P/Z platforms.
+
For more information on selecting a supported platform for your cluster installation, see "Selecting a cluster installation type".


.Procedure
. Verify that the `RetrievedUpdates` condition is `True` in the Cluster Version Operator (CVO) by running the following command:
+
[source,terminal]
----
$ oc get clusterversion/version -o=jsonpath="{.status.conditions[?(.type=='RetrievedUpdates')].status}"
----
+
If the `RetrievedUpates` condition is `False`, you can find supplemental information regarding the failure by using the following command:
+
[source,terminal]
----
$ oc adm upgrade
----
+
For more information about cluster version condition types, see "Understanding cluster version condition types".

ifndef::openshift-origin[]
. If the condition `RetrievedUpdates` is `False`, change the channel to `stable-<4.y>` or `fast-<4.y>` by running the following command:
+
[source,terminal]
----
$ oc adm upgrade channel <channel>
----
+
After setting the channel, verify if `RetrievedUpdates` is `True`.
+
For more information about channels, see "Understanding update channels and releases".
endif::openshift-origin[]

. Migrate to the multi-architecture payload by running the following command:
+
[source,terminal]
----
$ oc adm upgrade --to-multi-arch
----

.Verification

* Monitor the migration by running the following command:
+
[source,terminal]
----
$ oc adm upgrade
----
+
.Example output
[source,terminal]
----
working towards ${VERSION}: 106 of 841 done (12% complete), waiting on machine-config
----
+
[IMPORTANT]
====
Machine launches may fail as the cluster settles into the new state. To notice and recover when machines fail to launch, it is recommended that you deploy machine health checks. For more information about machine health checks and how to deploy them, see "About machine health checks".
====
+
. Optional: Retrieve more detailed information about the status of your update and monitor the migration by running the following command:
+
[source,terminal]
----
$ oc adm upgrade status
----
+
For more information about how to use the `oc adm upgrade status` command, see "Gathering cluster update status using oc adm upgrade status (Technology Preview)".

The migrations must be complete and all the cluster operators must be stable before you can add compute machine sets with different architectures to your cluster.
