// Module included in the following assemblies:
//
// * backup_and_restore/application_backup_and_restore/backing_up_and_restoring/restoring-applications.adoc

:_mod-docs-content-type: PROCEDURE
[id="oadp-creating-restore-hooks_{context}"]
= Creating restore hooks

[role="_abstract"]
Create restore hooks to run commands in a container in a pod by editing the `Restore` custom resource (CR).

You can create two types of restore hooks:

* An `init` hook adds an init container to a pod to perform setup tasks before the application container starts.
+
If you restore a Restic backup, the `restic-wait` init container is added before the restore hook init container.

* An `exec` hook runs commands or scripts in a container of a restored pod.

.Procedure

* Add a hook to the `spec.hooks` block of the `Restore` CR, as in the following example:
+
[source,yaml]
----
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: <restore>
  namespace: openshift-adp
spec:
  hooks:
    resources:
      - name: <hook_name>
        includedNamespaces:
        - <namespace>
        excludedNamespaces:
        - <namespace>
        includedResources:
        - pods
        excludedResources: []
        labelSelector:
          matchLabels:
            app: velero
            component: server
        postHooks:
        - init:
            initContainers:
            - name: restore-hook-init
              image: alpine:latest
              volumeMounts:
              - mountPath: /restores/pvc1-vm
                name: pvc1-vm
              command:
              - /bin/ash
              - -c
            timeout:
        - exec:
            container: <container>
            command:
            - /bin/bash
            - -c
            - "psql < /backup/backup.sql"
            waitTimeout: 5m
            execTimeout: 1m
            onError: Continue
----
+
where:

`<namespace>`:: Optional: Specifies an array of namespaces to which the hook applies. If this value is not specified, the hook applies to all namespaces.
`pods`:: Currently, pods are the only supported resource that hooks can apply to.
`labelSelector`:: Optional: This hook only applies to objects matching the label selector.
`timeout`:: Optional: Specifies the maximum length of time Velero waits for `initContainers` to complete.
`<container>`:: Optional: Specifies the container in which the command runs. If the container is not specified, the command runs in the first container in the pod.
`/bin/bash`:: Specifies the entrypoint for the init container being added.
`waitTimeout: 5m`:: Optional: Specifies how long to wait for a container to become ready. This should be long enough for the container to start and for any preceding hooks in the same container to complete. If not set, the restore process waits indefinitely.
`execTimeout: 1m`:: Optional: Specifies how long to wait for the commands to run. The default is `30s`.
`onError: Continue`:: Specifies the error handling behavior. Allowed values are `Fail` and `Continue`:
** `Continue`: Only command failures are logged.
** `Fail`: No more restore hooks run in any container in any pod. The status of the `Restore` CR will be `PartiallyFailed`.
