// Module included in the following assemblies:
//
// * backup_and_restore/application_backup_and_restore/oadp-advanced-topics/oadp-storage-class-mapping-main.adoc

:_mod-docs-content-type: PROCEDURE
[id="oadp-storage-class-mapping-oadp_{context}"]
= Mapping storage classes with OADP

[role="_abstract"]
Change the storage class of a persistent volume (PV) during a restore by configuring a storage class mapping in the Velero namespace. This helps you customize storage destinations when recovering applications with {oadp-short}.

To deploy ConfigMap with OADP, use the `change-storage-class-config` field. You must change the storage class mapping based on your cloud provider.

.Procedure
. Change the storage class mapping by running the following command:
+
[source,terminal]
----
$ cat change-storageclass.yaml
----
. Create a config map in the Velero namespace as shown in the following example:
+
.Example
[source,yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: change-storage-class-config
  namespace: openshift-adp
  labels:
    velero.io/plugin-config: ""
    velero.io/change-storage-class: RestoreItemAction
data:
  standard-csi: ssd-csi
----
. Save your storage class mapping preferences by running the following command:
+
[source,terminal]
----
$ oc create -f change-storage-class-config
----
