// Module included in the following assemblies:
//
// * osd_gcp_clusters/osd-creating-a-cluster-on-gcp-with-workload-identity-federation.adoc

:_mod-docs-content-type: PROCEDURE
[id="ocm-cli-manage-dns-zones_{context}"]
= Managing DNS zones

[role="_abstract"]
Managing your domain infrastructure is a key part of maintaining a healthy cluster environment. With the {cluster-manager} CLI (`ocm`), you can easily view and manage your existing managed DNS zones associated with your account. This allows you to keep track of your DNS configurations, make necessary updates, and ensure that your cluster's network settings are always up to date and secure.

.Procedure

* Use the following commands to view and manage existing managed DNS zones associated with your account.
** To list all the managed DNS zones, run the following command:
+
[source,terminal]
----
$ ocm gcp list dns-zones
----
** To view details about a specific managed DNS zone, run the following command, replacing `<dns_zone_id>` with the ID of the DNS zone you want to view:
+
[source,terminal]
----
$ ocm gcp describe dns-zone <dns_zone_id>
----
+
** To delete a managed DNS zone, run the following command, replacing `<dns_zone_id>` with the ID of the DNS zone you want to delete:
+
[source,terminal]
----
$ ocm gcp delete dns-zone <dns_zone_id>
----
+
[NOTE]
====
You cannot delete a managed DNS zone that is currently attached to an active {product-title} cluster.
====



