// Module included in the following assemblies:
//
// * service_mesh/v2x/ossm-reference-jaeger.adoc

:_mod-docs-content-type: REFERENCE
[id="ossm-config-ingester_{context}"]
= Ingester configuration options

[role="_abstract"]
Use the Ingester to read data from a Kafka topic and to write data to Elasticsearch. You do not need the Ingester for `allInOne` or `production` strategies.

.Jaeger parameters passed to the Ingester
[options="header"]
[cols="l, a, a"]
|===
|Parameter |Description |Values
|spec:
  ingester:
    options: {}
|Configuration options that define the Ingester service.
|

|options:
  deadlockInterval:
|Specifies the interval, in seconds or minutes, that the Ingester must wait for a message before terminating.
The deadlock interval is disabled by default (set to `0`), to avoid terminating the Ingester when no messages arrive during system initialization.
|Minutes and seconds, for example, `1m0s`. Default value is `0`.

|options:
  kafka:
    consumer:
      topic:
|The `topic` value names the Kafka setup. The collector writes to it. The Ingester reads from it.
|Label for the consumer. For example, `jaeger-spans`.

|options:
  kafka:
    consumer:
      brokers:
|Identifies the Kafka configuration used by the Ingester to consume the messages.
|Label for the broker, for example, `my-cluster-kafka-brokers.kafka:9092`.

|options:
  log-level:
|Logging level for the Ingester.
|Possible values: `debug`, `info`, `warn`, `error`, `fatal`, `dpanic`, `panic`.
|===

.Streaming Collector and Ingester example
[source,yaml]
----
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-streaming
spec:
  strategy: streaming
  collector:
    options:
      kafka:
        producer:
          topic: jaeger-spans
          brokers: my-cluster-kafka-brokers.kafka:9092
  ingester:
    options:
      kafka:
        consumer:
          topic: jaeger-spans
          brokers: my-cluster-kafka-brokers.kafka:9092
      ingester:
        deadlockInterval: 5
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
----
