// Module included in the following assemblies:
//
// * service_mesh/v2x/ossm-custom-resources.adoc

:_mod-docs-content-type: CONCEPT
[id="ossm-deploying-jaeger_{context}"]
= Deploying the distributed tracing platform

[role="_abstract"]
The {JaegerShortName} includes fixed deployment strategies. You set the strategy in the Jaeger custom resource (CR). When you create a {JaegerShortName} instance, the {JaegerName} Operator uses the CR to create what you need.

The {JaegerName} Operator supports these deployment strategies:

* *allInOne* (default) - Use this strategy for development, tests, and demos. Do not use it in production. Agent, Collector, and Query run in one process. By default it uses memory for storage. You can set this strategy in the SMCP.
+
[NOTE]
====
Memory storage does not last. If the Jaeger pod stops, restarts, or is replaced, you lose trace data. You cannot scale memory storage because each pod has its own memory. For data that persists, use the `production` or `streaming` strategies. Both use Elasticsearch for storage by default.
====

* *production* - Use this strategy when you need trace data kept long term and a layout that scales and stays up. Each back-end part runs on its own. You can add the Agent as a sidecar on your app. Query and Collector use a supported storage type. Today that type is Elasticsearch. You can run more than one copy of each part for speed and uptime. You can start this strategy in the SMCP. For full control, put your settings in the Jaeger CR and point the SMCP to that CR.

* *streaming* - This strategy adds a stream between the Collector and Elasticsearch. It eases load on storage when traffic is high. Other tools can also read span data from the stream (AMQ Streams and Apache Kafka). You cannot set this strategy in the SMCP. Create a Jaeger CR and link it from the SMCP.

[NOTE]
====
The streaming strategy requires an additional Red Hat subscription for AMQ Streams.
====

[id="ossm-deploying-jaeger-default_{context}"]
== Default {JaegerShortName} deployment

If you do not specify Jaeger configuration options, the `ServiceMeshControlPlane` resource will use the `allInOne` Jaeger deployment strategy by default. When using the default `allInOne` deployment strategy, set `spec.addons.jaeger.install.storage.type` to `Memory`. You can accept the defaults or specify additional configuration options under `install`.

.Control plane default Jaeger parameters (Memory)
[source,yaml, subs="attributes,verbatim"]
----
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  version: v{MaistraVersion}
  tracing:
    sampling: 10000
    type: Jaeger
  addons:
    jaeger:
      name: jaeger
      install:
        storage:
          type: Memory
----

[id="ossm-deploying-jaeger-production-min_{context}"]
== Production {JaegerShortName} deployment (minimal)

To use the default settings for the `production` deployment strategy, set `spec.addons.jaeger.install.storage.type` to `Elasticsearch` and specify additional configuration options under `install`. Note that the SMCP only supports configuring Elasticsearch resources and image name.

.Control plane default Jaeger parameters (Elasticsearch)
[source,yaml, subs="attributes,verbatim"]
----
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  version: v{MaistraVersion}
  tracing:
    sampling: 10000
    type: Jaeger
  addons:
    jaeger:
      name: jaeger  #name of Jaeger CR
      install:
        storage:
          type: Elasticsearch
        ingress:
          enabled: true
  runtime:
    components:
      tracing.jaeger.elasticsearch: # only supports resources and image name
        container:
          resources: {}
----


[id="ossm-deploying-jaeger-production_{context}"]
== Production {JaegerShortName} deployment (fully customized)

The SMCP supports only minimal Elasticsearch parameters. To fully customize your production environment and access all of the Elasticsearch configuration parameters, use the Jaeger custom resource (CR) to configure Jaeger.

Create and configure your Jaeger instance and set `spec.addons.jaeger.name` to the name of the Jaeger instance, in this example: `MyJaegerInstance`.

.Control plane with linked Jaeger production CR
[source,yaml, subs="attributes,verbatim"]
----
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  version: v{MaistraVersion}
  tracing:
    sampling: 1000
    type: Jaeger
  addons:
    jaeger:
      name: MyJaegerInstance #name of Jaeger CR
      install:
        storage:
          type: Elasticsearch
        ingress:
          enabled: true
----

[id="ossm-deploying-jaeger-streaming_{context}"]
== Streaming Jaeger deployment

To use the `streaming` deployment strategy, you create and configure your Jaeger instance first, then set `spec.addons.jaeger.name` to the name of the Jaeger instance, in this example: `MyJaegerInstance`.

.Control plane with linked Jaeger streaming CR
[source,yaml, subs="attributes,verbatim"]
----
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
spec:
  version: v{MaistraVersion}
  tracing:
    sampling: 1000
    type: Jaeger
  addons:
    jaeger:
      name: MyJaegerInstance  #name of Jaeger CR
----

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/documentation/en-us/red_hat_amq/7.6/html/using_amq_streams_on_openshift/index[Using AMQ Streams on OpenShift]
* link:https://kafka.apache.org/documentation/[Apache Kafka documentation]
