// Module included in the following assemblies:
//
// * service_mesh/v2x/ossm-reference-jaeger.adoc

:_mod-docs-content-type: REFERENCE
[id="ossm-distr-tracing-config-sampling_{context}"]
= Distributed tracing sampling configuration options

[role="_abstract"]
The {JaegerName} Operator sets sampling plans for tracers that use a remote sampler.

The system creates all traces, but only some are sampled. A sampled trace is kept for more work and storage.

[NOTE]
====
This does not apply if the Envoy proxy starts the trace. The proxy makes the sampling choice there. Jaeger sampling only applies when an app starts the trace with the client.
====

When a service gets a request with no trace data, the client starts a new trace. It picks a random trace ID. It samples based on the current plan. That choice applies to later requests in the same trace. Other services do not sample again.

{JaegerShortName} libraries support these samplers:

* *Probabilistic* - The sampler picks at random. The chance of sampling matches `sampling.param`. For example, `sampling.param=0.1` keeps about 1 in 10 traces.

* *Rate Limiting* - The sampler uses a rate limiter. Traces are sampled at a steady rate. For example, `sampling.param=2.0` keeps 2 traces per second.

.Jaeger sampling options
[options="header"]
[cols="l, a, a, a"]
|===
|Parameter |Description |Values |Default value
|spec:
 sampling:
  options: {}
    default_strategy:
    service_strategy:
|Configuration options that define the sampling strategies for tracing.
|
|If you do not provide configuration, the Collectors will return the default probabilistic sampling policy with 0.001 (0.1%) probability for all services.

|default_strategy:
  type:
service_strategy:
  type:
|Sampling strategy to use. See descriptions above.
|Valid values are `probabilistic`, and `ratelimiting`.
|`probabilistic`

|default_strategy:
  param:
service_strategy:
  param:
|Parameters for the selected sampling strategy.
|Decimal and integer values (0, .1, 1, 10)
|1
|===

This example sets the default plan to probabilistic sampling. It keeps half of the traces.

.Probabilistic sampling example
[source,yaml]
----
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: with-sampling
spec:
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 0.5
      service_strategies:
        - service: alpha
          type: probabilistic
          param: 0.8
          operation_strategies:
            - operation: op1
              type: probabilistic
              param: 0.2
            - operation: op2
              type: probabilistic
              param: 0.4
        - service: beta
          type: ratelimiting
          param: 5
----

If there are no user-supplied configurations, the {JaegerShortName} uses the following settings:

.Default sampling
[source,yaml]
----
spec:
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 1
----
