// Module included in the following assemblies:
//
// * service_mesh/v2x/ossm-reference-jaeger.adoc

:_mod-docs-content-type: REFERENCE
[id="ossm-config-jaeger-collector_{context}"]
= Jaeger Collector configuration options

[role="_abstract"]
The Jaeger Collector receives spans from the tracer. When you apply the `production` strategy, the Jaeger Collector sends them to Elasticsearch. When you apply the`streaming` strategy, it sends them to AMQ Streams.

Collectors do not store state. You can run many Collectors at the same time. You only need to set where Elasticsearch runs.

.Parameters used by the Operator to define the Jaeger Collector
[options="header"]
[cols="l, a, a"]
|===
|Parameter |Description |Values
|collector:
  replicas:
|Specifies the number of Collector replicas to create.
|Integer, for example, `5`
|===


.Configuration parameters passed to the Collector
[options="header"]
[cols="l, a, a"]
|===
|Parameter |Description |Values
|spec:
 collector:
  options: {}
|Configuration options that define the Jaeger Collector.
|

|options:
  collector:
    num-workers:
|The number of workers pulling from the queue.
|Integer, for example, `50`

|options:
  collector:
    queue-size:
|The size of the Collector queue.
|Integer, for example, `2000`

|options:
  kafka:
    producer:
      topic: jaeger-spans
|The `topic` value names the Kafka setup. The Collector writes to it. The Ingester reads from it.
|Label for the producer.

|options:
  kafka:
    producer:
      brokers: my-cluster-kafka-brokers.kafka:9092
|Names the Kafka setup for the Collector. If you omit brokers and AMQ Streams 1.4.0+ is installed, the {JaegerName} Operator creates Kafka for you.
|

|options:
  log-level:
|Logging level for the Collector.
|Possible values: `debug`, `info`, `warn`, `error`, `fatal`, `panic`.

|options:
  otlp:
    enabled: true
    grpc:
      host-port: 4317
      max-connection-age: 0s
      max-connection-age-grace: 0s
      max-message-size: 4194304
      tls:
        enabled: false
        cert: /path/to/cert.crt
        cipher-suites: "TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256"
        client-ca: /path/to/cert.ca
        reload-interval: 0s
        min-version: 1.2
        max-version: 1.3
|To accept OTLP/gRPC, explicitly enable the `otlp`. All the other options are optional.
|

|options:
  otlp:
    enabled: true
    http:
      cors:
        allowed-headers: [<header-name>[, <header-name>]*]
        allowed-origins: *
      host-port: 4318
      max-connection-age: 0s
      max-connection-age-grace: 0s
      max-message-size: 4194304
      read-timeout: 0s
      read-header-timeout: 2s
      idle-timeout: 0s
      tls:
        enabled: false
        cert: /path/to/cert.crt
        cipher-suites: "TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256"
        client-ca: /path/to/cert.ca
        reload-interval: 0s
        min-version: 1.2
        max-version: 1.3
|To accept OTLP/HTTP, explicitly enable the `otlp`. All the other options are optional.
|

|===
