// Module included in the following assemblies:
//
// * /networking/networking_overview/cidr-range-definitions.adoc

:_mod-docs-content-type: CONCEPT
[id="pod-cidr-description_{context}"]
= Pod classless inter-domain routing (CIDR)

[role="_abstract"]
In the pod CIDR field, you must specify the IP address range for pods.

ifdef::openshift-enterprise[]
The pod CIDR is the same as the `clusterNetwork` CIDR and the cluster CIDR.
endif::openshift-enterprise[]
ifdef::openshift-rosa,openshift-rosa-hcp,openshift-dedicated[]
Red{nbsp}Hat recommends, but this task is not mandatory, that the address block is the same between clusters. This does not create IP address conflicts.
endif::openshift-rosa,openshift-rosa-hcp,openshift-dedicated[]
The range must be large enough to accommodate your workload. The address block must not overlap with any external service accessed from within the cluster. The default is `10.128.0.0/14`.
ifdef::openshift-enterprise[]
You can expand the range after cluster installation.
endif::openshift-enterprise[]
