:_mod-docs-content-type: PROCEDURE

//included in restoring-3scale-api-management-by-using-oadp assembly

[id="restoring-the-backend-redis-database_{context}"]
= Restoring the back-end Redis database

[role="_abstract"]
Restore the back-end Redis database by creating a `Restore` custom resource (CR) that excludes non-essential cluster resources. This helps you to recover the Redis data store as part of the Red{nbsp}Hat 3scale API Management restoration process.

.Prerequisites

* You restored the Red{nbsp}Hat 3scale API Management operator resources, `Secret`, and APIManager custom resources.
* You restored the MySQL database.

.Procedure

. Delete the `backend-redis` deployment by running the following command:
+
[source,terminal]
----
$ oc delete deployment backend-redis -n threescale
----
+
[source,terminal]
----
Warning: apps.openshift.io/v1 deployment is deprecated in v4.14+, unavailable in v4.10000+

deployment.apps.openshift.io "backend-redis" deleted
----

. Create a YAML file with the following configuration to restore the Redis database:
+
.Example `restore-backend.yaml` file
[source,yaml]
----
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-backend
  namespace: openshift-adp
spec:
  backupName: redis-backup
  excludedResources:
    - nodes
    - events
    - events.events.k8s.io
    - backups.velero.io
    - restores.velero.io
    - resticrepositories.velero.io
    - csinodes.storage.k8s.io
    - volumeattachments.storage.k8s.io
    - backuprepositories.velero.io
  itemOperationTimeout: 1h0m0s
  restorePVs: true
----
+
where:

`redis-backup`:: Specifies the name of the Redis backup to restore.

. Restore the Redis database by running the following command:
+
[source,terminal]
----
$ oc create -f restore-backend.yaml
----
+
[source,terminal]
----
restore.velerio.io/restore-backend created
----

.Verification

* Verify that the `PodVolumeRestore` restore is completed by running the following command:
+
[source,terminal]
----
$ oc get podvolumerestores.velero.io -n openshift-adp
----

+
[source,terminal]
----
NAME                    NAMESPACE    POD                     UPLOADER TYPE   VOLUME                  STATUS      TOTALBYTES   BYTESDONE   AGE
restore-backend-jmrwx   threescale   backend-redis-1-bsfmv   kopia           backend-redis-storage   Completed   76123        76123       21m
----
