// Module included in the following assemblies:
//
// * support/rosa-troubleshooting-deployments.adoc
:_mod-docs-content-type: PROCEDURE
[id="rosa-troubleshooting-general-deployment-failure_{context}"]
= Connectivity issues on clusters with private network load balancers

[role="_abstract"]
{product-title} clusters created with version {product-version} deploy AWS Network Load Balancers (NLB) by default for the `default` ingress controller. In the case of a private NLB, the NLB client IP address preservation might drop connections where the source and destination are the same host. See the AWS documentation about how to link:https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-troubleshooting.html#loopback-timeout[Troubleshoot your Network Load Balancer]. This IP address preservation means that customer workloads co-located on the same node with the router pods might not be able to send traffic to the private NLB fronting the ingress controller router.

.Procedure

* To mitigate this impact, reschedule your workloads onto nodes separate from those where the router pods run. Or, rely on the internal pod and service networks for accessing other workloads co-located within the same cluster.
