// Module included in the following assemblies:
//
// * networking/ingress_load_balancing/configuring_ingress_cluster_traffic/controlling-incoming-traffic-gateway-listeners.adoc
//
:_mod-docs-content-type: PROCEDURE
[id="troubleshooting-listener-conditions_{context}"]
= Troubleshoot listener connections using status conditions

[role="_abstract"]
When a listener is not routing traffic as expected, you can review its `status` conditions to quickly diagnose and fix the configuration error. The listener `status` condition gives insight into its current state and any underlying issues preventing it from accepting traffic.

.Procedure

. Check the `status` conditions of your `Gateway` custom resource (CR) by running the following command:
+
[source,terminal]
----
$ oc describe gateway <gateway_cr> -n <namespace>
----
* `<gateway_cr>`: Specify the name of your gateway.
* `<namespace>`: Specify the namespace where the gateway resides.
+
For details on how to interpret the output and resolve common errors, see xref:gateway-listener-troubleshooting-reference_{context}[].