// Module included in the following assemblies:
//
// * updating/updating_a_cluster/updating-cluster-web-console.adoc

:_mod-docs-content-type: PROCEDURE
[id="update-changing-update-server-web_{context}"]
= Changing the update server by using the web console

[role="_abstract"]
You can change the update server your cluster uses to retrieve information about update paths.

ifndef::openshift-origin[]
Changing the update server is optional. If you have an OpenShift Update Service (OSUS) installed and configured locally, you must set the URL for the server as the `upstream` to use the local server during updates.
endif::openshift-origin[]
ifdef::openshift-origin[]
Changing the update server is optional.
endif::openshift-origin[]

.Prerequisites
* You have access to the cluster with `cluster-admin` privileges.

* You have access to the {product-title} web console.

.Procedure

. On the web console, navigate to *Administration* -> *Cluster Settings* and click *version*.
. Click the *YAML* tab and then edit the `upstream` parameter value:
+
.Example YAML snippet
[source,yaml]
----
  ...
  spec:
    clusterID: db93436d-7b05-42cc-b856-43e11ad2d31a
    upstream: '<update_server_url>'
  ...
----
+
Replace `<update_server_url>` with the URL for the update server.
+
The default `upstream` value is `\https://api.openshift.com/api/upgrades_info/v1/graph`.

. Click *Save*.
