// Module included in the following assemblies:
//
// * updating/updating_a_cluster/control-plane-only-update.adoc

:_mod-docs-content-type: CONCEPT
[id="updating-control-plane-only-olm-operators_{context}"]
= Control Plane Only updates for layered products and Operators installed through Operator Lifecycle Manager

[role="_abstract"]
There are additional steps to consider when performing Control Plane Only updates for clusters with either layered products or Operators installed through Operator Lifecycle Manager (OLM).

Layered products refer to products that are made of multiple underlying products that are intended to be used together and cannot be broken into individual subscriptions. For examples of layered {product-title} products, see link:https://access.redhat.com/support/policy/updates/openshift/#layered[Layered Offering On OpenShift].

As you perform a Control Plane Only update for the clusters of layered products and those of Operators that have been installed through OLM, you must complete the following actions:

. You have updated all Operators previously installed through Operator Lifecycle Manager (OLM) to a version that is compatible with your target release. Updating the Operators ensures they have a valid update path when the default software catalogs switch from the current minor version to the next during a cluster update. See "Updating installed Operators" for more information on how to check compatibility and, if necessary, update the installed Operators.

. Confirm the cluster version compatibility between the current and intended Operator versions. You can verify which versions your OLM Operators are compatible with by using the link:https://access.redhat.com/labs/ocpouic/?operator=logging&&ocp_versions=4.10,4.11,4.12[Red{nbsp}Hat {product-title} Operator Update Information Checker].

For example, the following high level steps describe how to perform a Control Plane Only update from <4.y> to <4.y+2> for {rh-storage} (ODF). This can be done through the CLI or web console. For information about how to update clusters through your desired interface, see "Control Plane Only update using the web console" and "Control Plane Only update using the CLI".

. Pause the worker machine pools.
. Update {product-title} from <4.y> to <4.y+1>.
. Update ODF from <4.y> to <4.y+1>.
. Update {product-title} from <4.y+1> to <4.y+2>.
. Update ODF to <4.y+2>.
. Unpause the worker machine pools.

[NOTE]
====
The update to ODF <4.y+2> can happen before or after worker machine pools have been unpaused.
====







