// Module included in the following assemblies:
//
// * virt/nodes/virt-node-maintenance.adoc

:_mod-docs-content-type: CONCEPT
[id="virt-about-node-maintenance-operator_{context}"]
= About the Node Maintenance Operator

[role="_abstract"]
The Node Maintenance Operator watches for new or deleted `NodeMaintenance` custom resources (CRs). When a new `NodeMaintenance` CR is detected, no new workloads are scheduled, and the node is cordoned off from the rest of the cluster. All pods that can be evicted are evicted from the node. When a `NodeMaintenance` CR is deleted, the node that is referenced in the CR is made available for new workloads.

Using a `NodeMaintenance` CR for node maintenance tasks achieves the same results as the `oc adm cordon` and `oc adm drain` commands using standard {product-title} custom resource processing.

[NOTE]
====
The `node-maintenance-operator` (NMO) is no longer shipped with {VirtProductName}. It is deployed as a standalone Operator from the software catalog in the {product-title} web console or by using the {oc-first}.
====
