// Module included in the following assemblies:
//
// * virt/about_virt/about-virt.adoc
// * virt/virt_release_notes/virt-2-4-release-notes.adoc

:_mod-docs-content-type: CONCEPT
[id="virt-supported-cluster-version_{context}"]
= Supported cluster versions for {VirtProductName}

[role="_abstract"]
ifdef::openshift-dedicated[]
{VirtProductName} on {product-title} on {gcp-short} requires {product-title} 4.21.5 or later and {VirtProductName} Operator 4.21.1 or later.
endif::openshift-dedicated[]
ifndef::openshift-dedicated[]
{VirtProductName} {VirtVersion} is supported for use on {product-title} {product-version} clusters. To use the latest z-stream release of {VirtProductName}, you must first upgrade to the latest version of {product-title}.
endif::openshift-dedicated[]
The latest stable release of {VirtProductName} {VirtVersion} is {HCOVersion}.


ifdef::openshift-rosa,openshift-rosa-hcp[]
[NOTE]
====
{VirtProductName} is currently available on x86-64 CPUs. Arm-based nodes are not yet supported.
====
endif::openshift-rosa,openshift-rosa-hcp[]
