// Module included in the following assemblies:
//
// * virt/vm_networking/virt-networking-overview.adoc

:_mod-docs-content-type: REFERENCE
[id="virt-nw-overview-connect-vm-to-physical-nw_{context}"]                                
= Connect to the provider's physical network

[role="_abstract"]
To give virtual machines (VMs) access to the internet or other physical devices, you configure the node network, define the secondary network, and attach the VM to the secondary network.


Connect a VM to the physical network by using an Open vSwitch bridge:: You can connect a VM to the physical network infrastructure by configuring an OVN-Kubernetes secondary user-defined network (UDN) with the localnet topology.
+
A localnet topology connects the secondary network to the physical underlay. This enables both east-west cluster traffic and access to services running outside the cluster, but it requires additional configuration of the underlying Open vSwitch (OVS) bridge on cluster nodes.
+
Cluster administrators can use the following steps to configure the localnet UDN:

. Install the Kubernetes NMState Operator which provides a state-driven network configuration across cluster nodes.
. Use the `NodeNetworkConfigurationPolicy` custom resource (CR) to configure OVS bridges and add the appropriate bridge mappings on the nodes.
. Use the `ClusterUserDefinedNetwork` CR from the UDN API to attach their workload to the underlay network through the OVS bridges configured in the previous step.


// Hiding from ROSA/OSD as Linux Bridge not supported
ifndef::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]
Connect a VM to the physical network by using a Linux bridge:: Install the Kubernetes NMState Operator to configure Linux bridges, VLANs, and bonding for your secondary networks. The OVN-Kubernetes `localnet` topology is the recommended way of connecting a VM to the underlying physical network, but {VirtProductName} also supports Linux bridge networks.
+
[NOTE]
====
You cannot directly attach to the default machine network when using Linux bridge networks.
====
+
You can create a Linux bridge network and attach a VM to the network by performing the following steps:

. Prepare the node network by creating a Linux bridge node network configuration policy (NNCP).
. Define the secondary Linux bridge network by creating a network attachment definition (NAD).
. Attach the VM to the Linux bridge network.
endif::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]

// Hiding from ROSA/OSD as SR-IOV not supported
ifndef::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]
Connect a VM to the physical network by using an SR-IOV device:: You can use Single Root I/O Virtualization (SR-IOV) network devices with additional networks on your {product-title} cluster installed on bare metal or {rh-openstack-first} infrastructure for applications that require high bandwidth or low latency.
+
You must install the SR-IOV Network Operator on your cluster to manage SR-IOV network devices and network attachments.
+
You can connect a VM to an SR-IOV network by performing the following steps:

. Configure an SR-IOV physical network device by creating a `SriovNetworkNodePolicy` CR.
. Define the SR-IOV secondary network by creating an `SriovNetwork` object.
. Connect the VM to the SR-IOV network by including the network details in the VM configuration.
endif::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]

// Hiding in ROSA/OSD as not supported
ifndef::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]
Connect a VM to the physical network by using DPDK drivers with SR-IOV hardware:: The Data Plane Development Kit (DPDK) provides a set of libraries and drivers for fast packet processing. You can configure clusters and VMs to run DPDK workloads over SR-IOV networks by performing the following steps:

. Configure the node hardware.
. Configure the VM namespace for DPDK.
. Configure the VM and guest OS to run DPDK applications.
endif::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]