// Module included in the following assemblies:
//
// * virt/vm_networking/virt-networking-overview.adoc

:_mod-docs-content-type: REFERENCE
[id="virt-nw-overview-manage-vm-nw-config_{context}"]                                
= Manage VM network interface configuration

[role="_abstract"]
Manage virtual machine (VM) network configuration to scale connectivity without incurring application downtime, troubleshoot network latency, define and automate management of MAC address pools, configure IP addresses, and isolate live migration traffic.


ifndef::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]
Hot plug secondary network interfaces:: You can add or remove secondary network interfaces without stopping your VM. {VirtProductName} supports hot plugging and hot unplugging for secondary interfaces that use bridge binding and the VirtIO device driver. {VirtProductName} also supports hot plugging secondary interfaces that use the SR-IOV binding.
endif::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]

ifdef::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]
Hot plug secondary network interfaces:: You can add or remove secondary network interfaces without stopping your VM. {VirtProductName} supports hot plugging and hot unplugging for secondary interfaces that use bridge binding and the OVN-Kubernetes `layer2` topology.
endif::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]

Access a VM by using its external FQDN:: You can access a virtual machine (VM) that is attached to a secondary network interface from outside the cluster by using its fully qualified domain name (FQDN). To connect to a VM by using its external FQDN, you must configure the DNS server, retrieve the cluster FQDN, and then connect to the VM by using the `ssh` command.

Manage the link state of a VM network interface:: You can manage the link state of a primary or secondary VM network interface by using the {product-title} web console or the command line. By specifying the link state, you can logically connect or disconnect the virtual network interface controller (vNIC) from a network.
+
[NOTE]
====
{VirtProductName} does not support link state management for Single Root I/O Virtualization (SR-IOV) secondary network interfaces and their link states are not reported.
====

Configure and view VM IP address:: You can configure the IP address of a secondary network interface when you create a VM. The IP address is provisioned with cloud-init. You can view the IP address of a VM by using the {product-title} web console or the command line. The network information is collected by the QEMU guest agent.

Manage MAC address pools for VM network interfaces:: The KubeMacPool component allocates MAC addresses for VM network interfaces from a shared MAC address pool. This ensures that each network interface is assigned a unique MAC address. A virtual machine instance created from that VM retains the assigned MAC address across reboots.

ifndef::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]
Configure a dedicated network for live migration:: You can configure a dedicated Multus network for live migration. A dedicated network minimizes the effects of network saturation on tenant workloads during live migration.
endif::openshift-rosa,openshift-dedicated,openshift-rosa-hcp[]

