// Module included in the following assemblies:
//
// * virt/updating/upgrading-virt.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-monitoring-upgrade-status_{context}"]
= Monitoring update status

[role="_abstract"]
To monitor the status of a {CNVOperatorDisplayName} update, watch the cluster service version (CSV) `PHASE`. You can also monitor the CSV conditions in the web console or by using the CLI.

[NOTE]
====
The `PHASE` and conditions values are approximations that are based on available information.
====

.Prerequisites

* You have logged in to the {product-title} cluster as a cluster administrator.
* You have installed the {oc-first}.

.Procedure

. Run the following command:
+
[source,terminal,subs="attributes+"]
----
$ oc get csv -n {CNVNamespace}
----

. Review the output, checking the `PHASE` field. For example:
+
[source,terminal,subs="attributes+"]
----
VERSION  REPLACES                                        PHASE
4.9.0    kubevirt-hyperconverged-operator.v4.8.2         Installing
4.9.0    kubevirt-hyperconverged-operator.v4.9.0         Replacing
----

. Optional: Monitor the aggregated status of all {VirtProductName} component
conditions by running the following command:
+
[source,terminal,subs="attributes+"]
----
$ oc get {HCOCliKind} kubevirt-hyperconverged -n {CNVNamespace} \
  -o=jsonpath='{range .status.conditions[*]}{.type}{"\t"}{.status}{"\t"}{.message}{"\n"}{end}'
----
+
A successful upgrade results in the following output:
+
[source,terminal]
----
ReconcileComplete  True  Reconcile completed successfully
Available          True  Reconcile completed successfully
Progressing        False Reconcile completed successfully
Degraded           False Reconcile completed successfully
Upgradeable        True  Reconcile completed successfully
----
