// Module included in the following assemblies:
//
// * virt/vm_networking/virt-connecting-vm-to-linux-bridge.adoc
// * virt/post_installation_configuration/virt-post-install-network-config.adoc
//This file contains UI elements and/or package names that need to be updated.

:_mod-docs-content-type: PROCEDURE
[id="virt-creating-linux-bridge-nad-web_{context}"]
= Creating a Linux bridge NAD by using the web console

[role="_abstract"]
Use the {product-title} web console to create a network attachment definition (NAD) that connects pods and virtual machines to a layer-2 network.

[WARNING]
====
Configuring IP address management (IPAM) in a network attachment definition for virtual machines is not supported.
====

.Procedure

. In the web console, click *Networking* -> *NetworkAttachmentDefinitions*.
. Click *Create Network Attachment Definition*.
+
[NOTE]
====
The network attachment definition must be in the same namespace as the pod or virtual machine.
====
+
. Enter a unique *Name* and optional *Description*.
. Select *CNV Linux bridge* from the *Network Type* list.
. Enter the name of the bridge in the *Bridge Name* field.
. Optional: If the resource has VLAN IDs configured, enter the ID numbers in the *VLAN Tag Number* field.
ifndef::openshift-dedicated[]
+
[NOTE]
====
Open Systems Adapter (OSA) interfaces on {ibm-z-name} do not support VLAN filtering and drop VLAN-tagged traffic. Avoid using VLAN-tagged NADs with OSA interfaces.
====
+
endif::openshift-dedicated[]
. Optional: Select *MAC Spoof Check* to enable MAC spoof filtering. This feature provides security against a MAC spoofing attack by allowing only a single MAC address to exit the pod.
. Click *Create*.
