// Module included in the following assemblies:
//
// * virt/updating/upgrading-virt.adoc

:_mod-docs-content-type: CONCEPT
[id="virt-about-control-plane-only-updates_{context}"]
= Control Plane Only updates

[role="_abstract"]
A Control Plane Only update allows you to update between Extended Update Support (EUS) versions of {product-title} while preventing virtual machine workloads from updating during the intermediate upgrade.

Every even-numbered minor version of {product-title} is an Extended Update Support (EUS) version. However, Kubernetes requires minor version updates to occur sequentially. As a result, you cannot update directly from one EUS version to the next.

To move between EUS versions, you must first update {VirtProductName} to the latest z-stream release of the next odd-numbered minor version. After the cluster updates to the target EUS version of {product-title}, the corresponding update for {VirtProductName} becomes available. You can then update {VirtProductName} to the target EUS version.

[NOTE]
====
You can directly update {VirtProductName} to the latest z-stream release of your current minor version without applying each intermediate z-stream update.
====

For more information about EUS versions, see the link:https://access.redhat.com/support/policy/updates/openshift[{product-title} Life Cycle Policy].
