// Module included in the following assemblies:
//
// * virt/support/virt-monitoring-vm-health.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-define-http-readiness-probe_{context}"]

= Defining an HTTP readiness probe

[role="_abstract"]
You can define an HTTP readiness probe by setting the `spec.readinessProbe.httpGet` field of the virtual machine (VM) configuration.

.Prerequisites
* You have installed the {oc-first}.

.Procedure
. Include details of the readiness probe in the VM configuration file.
+
Sample readiness probe with an HTTP GET test:
+
[source,yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  name: fedora-vm
  namespace: example-namespace
# ...
spec:
  template:
    spec:
      readinessProbe:
        httpGet:
          port: 1500
          path: /healthz
          httpHeaders:
          - name: Custom-Header
            value: Awesome
        initialDelaySeconds: 120
        periodSeconds: 20
        timeoutSeconds: 10
        failureThreshold: 3
        successThreshold: 3
# ...
----
+
* `spec.template.spec.readinessProbe.httpGet` defines the HTTP GET request to perform to connect to the VM.
* `spec.template.spec.readinessProbe.httpGet.port` defines the port of the VM that the probe queries. In the above example, the probe queries port 1500.
* `spec.template.spec.readinessProbe.httpGet.path` defines the path to access on the HTTP server. In the above example, if the handler for the server’s /healthz path returns a success code, the VM is considered to be healthy. If the handler returns a failure code, the VM is removed from the list of available endpoints.
* `spec.template.spec.readinessProbe.initialDelaySeconds` defines the time, in seconds, after the VM starts before the readiness probe is initiated.
* `spec.template.spec.readinessProbe.periodSeconds` defines the delay, in seconds, between performing probes. The default delay is 10 seconds. This value must be greater than `timeoutSeconds`.
* `spec.template.spec.readinessProbe.timeoutSeconds` defines the number of seconds of inactivity after which the probe times out and the VM is assumed to have failed. The default value is 1. This value must be lower than `periodSeconds`.
* `spec.template.spec.readinessProbe.failureThreshold` defines the number of times that the probe is allowed to fail. The default is 3. After the specified number of attempts, the pod is marked `Unready`.
* `spec.template.spec.readinessProbe.successThreshold` defines the number of times that the probe must report success, after a failure, to be considered successful. The default is 1.

. Create the VM by running the following command:
+
[source,terminal]
----
$ oc create -f <file_name>.yaml
----
