// Module included in the following assemblies:
//
// * virt/support/virt-monitoring-vm-health.adoc

:_mod-docs-content-type: PROCEDURE
[id="virt-define-guest-agent-ping-probe_{context}"]

= Defining a guest agent ping probe

[role="_abstract"]
You can define a guest agent ping probe by setting the `spec.readinessProbe.guestAgentPing` field of the virtual machine (VM) configuration.

.Prerequisites

* The QEMU guest agent must be installed and enabled on the virtual machine.
* You have installed the {oc-first}.

.Procedure

. Include details of the guest agent ping probe in the VM configuration file. For example:
+
[source,yaml]
----
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  name: fedora-vm
  namespace: example-namespace
# ...
spec:
  template:
    spec:
      readinessProbe:
        guestAgentPing: {} 
        initialDelaySeconds: 120
        periodSeconds: 20
        timeoutSeconds: 10 
        failureThreshold: 3
        successThreshold: 3
# ...
----
+
* `spec.template.spec.readinessProbe.guestAgentPing` defines the guest agent ping probe to connect to the VM.
* `spec.template.spec.readinessProbe.initialDelaySeconds` defines the time, in seconds, after the VM starts before the guest agent probe is initiated. This value is optional.
* `spec.template.spec.readinessProbe.periodSeconds` defines the delay, in seconds, between performing probes. The default delay is 10 seconds. This value must be greater than `timeoutSeconds`. This value is optional
* `spec.template.spec.readinessProbe.timeoutSeconds` defines the number of seconds of inactivity after which the probe times out and the VM is assumed to have failed. The default value is 1. This value must be lower than `periodSeconds`. This value is optional.
* `spec.template.spec.readinessProbe.failureThreshold` defines the number of times that the probe is allowed to fail. The default is 3. After the specified number of attempts, the pod is marked `Unready`. This value is optional.
* `spec.template.spec.readinessProbe.successThreshold` defines the number of times that the probe must report success, after a failure, to be considered successful. The default is 1. This value is optional.

. Create the VM by running the following command:
+
[source,terminal]
----
$ oc create -f <file_name>.yaml
----
