:_mod-docs-content-type: ASSEMBLY
[id="microshift-deleting-resource-manifests"]
= Deleting or updating Kustomize manifest resources
include::_attributes/attributes-microshift.adoc[]
:context: microshift-deleting-resource-manifests

toc::[]

[role="_abstract"]
When creating new manifests in {microshift-short}, you can use manifest resource deletion to remove or update old objects, ensuring there are no conflicts or issues.

{microshift-short} supports the deletion of manifest resources in the following situations:

* Manifest removal: Manifests can be removed when you need to completely remove a resource from the node.
* Manifest upgrade: During an application upgrade, some resources might need to be removed while others are retained to preserve data.

[IMPORTANT]
====
Manifest files placed in the `delete` subdirectories are not automatically removed and require manual deletion. Only the resources listed in the manifest files placed in the delete subdirectories are deleted.
====

include::modules/microshift-manifests-deletion-overview.adoc[leveloffset=+1]

include::modules/microshift-manifests-removal-scenario-rpm.adoc[leveloffset=+2]

include::modules/microshift-manifests-removal-scenario-ostree.adoc[leveloffset=+2]

include::modules/microshift-manifests-upgrade-scenario-rpm.adoc[leveloffset=+2]

include::modules/microshift-manifests-upgrade-scenario-ostree.adoc[leveloffset=+2]

[id="additional-resources_microshift-deleting-resource-manifests_{context}"]
[role="_additional-resources"]
== Additional resources
* xref:../microshift_running_apps/microshift-applications.adoc#applications-with-microshift[Using Kustomize manifests to deploy applications]