:_mod-docs-content-type: ASSEMBLY
[id="backing-up-and-restoring-3scale-api-management-by-using-oadp"]
= Backing up and restoring 3scale API Management by using OADP
include::_attributes/common-attributes.adoc[]
:context: backing-up-and-restoring-3scale-api-management-by-using-oadp

toc::[]

[role="_abstract"]
Back up and restore Red{nbsp}Hat 3scale API Management deployments by using {oadp-first} to protect application resources, persistent volumes, and configurations. This helps you to safeguard your 3scale components for disaster recovery.

You can deploy 3scale components on-premise, in the cloud, as a managed service, or in any combination based on your requirements.

With {oadp-first}, you can safeguard 3scale API Management deployments by backing up application resources, persistent volumes, and configurations. 

[NOTE]
====
You can use the {oadp-first} Operator to back up and restore your 3scale API Management on-cluster storage databases without affecting your running services
====

You can configure {oadp-short} to perform the following operations with 3scale API Management:

* Create a backup of 3scale components. For more details, see _Backing up 3scale API Management_.

* Restore the components to scale up the 3scale operator and deployment. For more details, see _Restoring 3scale API Management_.

[role="_additional-resources"]
.Additional resources

* xref:../../../backup_and_restore/application_backup_and_restore/oadp-3scale/backing-up-3scale-api-management-by-using-oadp.adoc#backing-up-3scale-api-management-by-using-oadp[Backing up 3scale API Management]

* xref:../../../backup_and_restore/application_backup_and_restore/oadp-3scale/restoring-3scale-api-management-by-using-oadp.adoc#restoring-3scale-api-management-by-using-oadp[Restoring 3scale API Management]

