:_mod-docs-content-type: ASSEMBLY
[id="learning-getting-started-autoscaling"]
= Autoscaling

include::_attributes/attributes-openshift-dedicated.adoc[]
:context: cloud-experts-getting-started-autoscaling

toc::[]
[role="_abstract"]
Configure cluster autoscaling to improve performance and ensure that your environment dynamically adapts to changing workload demands. The cluster autoscaler adds or removes worker nodes from a cluster based on pod resources.

The cluster autoscaler increases the size of the cluster when:

* Pods fail to schedule on the current nodes due to insufficient resources.
* Another node is necessary to meet deployment needs.

It does not increase the cluster resources beyond the limits that you specify. 

The cluster autoscaler decreases the size of the cluster when:

* Some nodes are consistently not needed for a significant period. For example, when a node has low resource use and all of its important pods can fit on other nodes.

include::modules/learning-getting-started-autoscaling-cli.adoc[leveloffset=+1]
include::modules/learning-getting-started-autoscaling-web-ui.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources

* link:https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/latest/html-single/cluster_administration/index#rosa-nodes-about-autoscaling-nodes[Cluster autoscaler]